#!/usr/bin/env python3
"""Generate the RISC-V extension name reference from a Unified Database checkout."""
from __future__ import annotations

import argparse
import re
from pathlib import Path

FIELD_RE = re.compile(r"^(name|long_name):\s*(.*?)\s*$")

def unquote(value: str) -> str:
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {'\"', "'"}:
        return value[1:-1]
    return value

def read_extension(path: Path) -> tuple[str, str]:
    fields: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        match = FIELD_RE.match(line)
        if match and match.group(1) not in fields:
            fields[match.group(1)] = unquote(match.group(2))
        if "name" in fields and "long_name" in fields:
            break
    if "name" not in fields or "long_name" not in fields:
        raise ValueError(f"missing name or long_name in {path}")
    return fields["name"], fields["long_name"]

def escape_cell(value: str) -> str:
    return value.replace("|", "\\|")

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("udb", type=Path, help="path to a riscv-unified-db checkout")
    parser.add_argument("--output", type=Path, default=Path("src/extension-reference.adoc"))
    args = parser.parse_args()

    ext_dir = args.udb / "spec/std/isa/ext"
    if not ext_dir.is_dir():
        parser.error(f"extension directory not found: {ext_dir}")

    entries = sorted((read_extension(path) for path in ext_dir.glob("*.yaml")), key=lambda item: item[0].lower())
    lines = [
        "// Generated by scripts/generate-extension-reference.py from riscv-unified-db.",
        "// Do not edit this table by hand; regenerate it from the canonical UDB data.",
        "",
        "[[extension-reference]]",
        "== RISC-V extension reference",
        "",
        "The extension names and long forms below are generated from extension metadata in the RISC-V Unified Database (UDB).",
        "",
        '[cols="1,4",options="header"]',
        "|===",
        "| Extension | Long name",
        "",
    ]
    for name, long_name in entries:
        lines.append(f"| `{escape_cell(name)}` | {escape_cell(long_name)}")
    lines.extend(["|===", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.output} with {len(entries)} extensions")

if __name__ == "__main__":
    main()
